Fix executable not found error
thoth-station/thoth-pre-commit-hook pull request #16
Opened 2022-06-24 08:58 UTC by mayaCostantini

## This introduces a breaking change

- No

## This should yield a new module release

- Yes

## This Pull Request implements

Fix error caused by executable entrypoint not found.

2022-06-24 08:58 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mayacostantini** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-pre-commit-hook).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-pre-commit-hook/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mayacostantini"]} -->

2022-06-24 09:05 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mayacostantini** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-pre-commit-hook).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-pre-commit-hook/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mayacostantini"]} -->

2022-06-24 09:53 UTC, sesheta commented
@mayaCostantini: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 6d282adc889397208509d3005469113752ca83ec | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_thoth-pre-commit-hook/16/pre-commit/1540269909366280192) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-pre-commit-hook&pr=16). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AmayaCostantini). Please help us and [open an issue](https://github.com/thoth-station/thoth-pre-commit-hook/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-24 13:00 UTC, harshad16 approved these changes
/lgtm
/approve

2022-06-24 13:00 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/thoth-pre-commit-hook/pull/16#pullrequestreview-1018446379" title="Approved">harshad16</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mayacostantini** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-pre-commit-hook).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-pre-commit-hook/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mayacostantini"]} -->

2022-06-24 14:25 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2022-06-24 16:40 UTC, harshad16 requested changes
very great work
here is the suggestion for the error we are facing

2022-06-24 16:40 UTC, harshad16 commented on setup.py
> +            "thoth-advise = thoth.thoth_pre_commit_hook.thoth_advise:main"
As we discuss over the chat this doesnt fucntion as required.
Reason being https://packaging.python.org/en/latest/specifications/entry-points/, entry point looks for a format of `module.object`
and `thoth.thoth_pre_commit_hook` is being intrepret as module, where only `thoth_pre_commit_hook` is the module.

we can change this in the following way:

```
entry_points={
        "console_scripts": ["thoth-advise = thoth_pre_commit_hook:thoth_advise.main"]
    },
packages=["thoth_pre_commit_hook"],
package_dir={
        "thoth_pre_commit_hook": "./thoth/thoth_pre_commit_hook",
    },
```
here we are making setup py aware explicitly that `thoth_pre_commit_hook` is the module 
and we would like to run the file from this module

2022-06-24 16:40 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mayacostantini** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-pre-commit-hook).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-pre-commit-hook/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mayacostantini"]} -->

2022-06-27 09:53 UTC, mayaCostantini commented
Thanks for the review @harshad16, this should be good now. Feel free to test with the last revision though :+1:

2022-06-27 13:01 UTC, harshad16 approved these changes
/lgtm
thanks :100:

2022-06-27 13:12 UTC, merged